"""user-location

Revision ID: 49895fb41fc5
Revises: e1645bda4ec9
Create Date: 2025-12-03 11:44:29.128658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49895fb41fc5'
down_revision = 'e1645bda4ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
